### ISSUE TITLE
POST returnCheck return 500 error

### ISSUE THREAD

**Issue by mingleeeeee** [s1031432/TKBHacker#1]
您好
console回報 POST /book-seat/student/bookSeat/returnCheck **500 server internal error**
log為 HTTP Status 500 - Request processing failed; nested exception is **java.lang.NullPointerException**
似乎是在post returnCheck的部分出了問題
想請問有任何可能的解決方法嗎
謝謝!

**Comment by s1031432** [comment]
把你的大碩帳密給我我修改看看
我的大碩帳號沒有課可以預約了

從我的iPhone傳送

Ming <notifications@github.com> 於 2020年7月23日 15:20 寫道：

﻿

您好
console回報 POST /book-seat/student/bookSeat/returnCheck 500 server internal error
log為 HTTP Status 500 - Request processing failed; nested exception is java.lang.NullPointerException
似乎是在post returnCheck的部分出了問題
想請問有任何可能的解決方法嗎
謝謝!

**Comment by mingleeeeee** [comment]
好的
麻煩您給我email

**Comment by s1031432** [comment]
ty80517@gmail.com

從我的iPhone傳送

Ming <notifications@github.com> 於 2020年7月23日 15:41 寫道：

﻿

好的
麻煩您給我email

**Comment by mingleeeeee** [comment]
已傳送
請問有收到嗎

**Comment by s1031432** [comment]
有，我今天有空看看，不一定處理的好喔

從我的iPhone傳送

Ming <notifications@github.com> 於 2020年7月23日 22:44 寫道：

﻿

已傳送
請問有收到嗎
